import { UI } from "../constants/ui.js";

const mono = "'JetBrains Mono',monospace";

export const css = {
  root: {
    minHeight:"100vh",
    position:"relative",
    overflow:"hidden",
    background:"linear-gradient(180deg, #fbf5ec 0%, #f6ede1 48%, #efdfcc 100%)",
    color:UI.ink,
    fontFamily:"'Noto Serif SC', Georgia, serif",
  },
  ambient: { position:"fixed", inset:0, pointerEvents:"none", overflow:"hidden" },
  glowOne: { position:"absolute", top:"-120px", right:"-40px", width:"400px", height:"400px", borderRadius:"999px", background:"radial-gradient(circle, rgba(224,182,143,0.15) 0%, rgba(224,182,143,0) 70%)" },
  glowTwo: { position:"absolute", top:"180px", left:"-120px", width:"350px", height:"350px", borderRadius:"999px", background:"radial-gradient(circle, rgba(216,162,161,0.10) 0%, rgba(216,162,161,0) 68%)" },
  glowThree: { position:"absolute", bottom:"-140px", right:"8%", width:"420px", height:"420px", borderRadius:"999px", background:"radial-gradient(circle, rgba(214,176,114,0.10) 0%, rgba(214,176,114,0) 72%)" },
  center: { display:"flex",justifyContent:"center",alignItems:"center",minHeight:"100vh",background:UI.bg },
  dim: { color:UI.inkMute,fontSize:"16px" },
  nav: {
    display:"flex",
    gap:"6px",
    padding:"14px 14px 10px",
    borderBottom:"1px solid "+UI.lineSoft,
    overflowX:"auto",
    WebkitOverflowScrolling:"touch",
    position:"sticky",
    top:0,
    zIndex:10,
    background:"rgba(251,245,236,0.82)",
    backdropFilter:"blur(14px)",
  },
  navOff: {
    padding:"9px 13px",
    background:"rgba(255,250,244,0.76)",
    border:"1px solid "+UI.lineSoft,
    borderRadius:"999px",
    color:UI.inkSoft,
    fontSize:"13px",
    cursor:"pointer",
    display:"flex",
    alignItems:"center",
    gap:"5px",
    whiteSpace:"nowrap",
    boxShadow:UI.shadowSoft,
  },
  navOn: {
    padding:"9px 13px",
    background:"linear-gradient(180deg, rgba(255,249,241,0.98) 0%, rgba(243,226,204,0.95) 100%)",
    border:"1px solid rgba(201,134,99,0.26)",
    borderRadius:"999px",
    color:UI.accentStrong,
    fontSize:"13px",
    cursor:"pointer",
    display:"flex",
    alignItems:"center",
    gap:"5px",
    whiteSpace:"nowrap",
    boxShadow:"0 10px 24px rgba(201,134,99,0.14)",
  },
  body: { position:"relative", zIndex:1, padding:"24px 18px 84px", maxWidth:"1180px", margin:"0 auto" },
  dateWrap: { marginBottom:"18px" },
  dateBar: {
    display:"grid",
    gridTemplateColumns:"auto 1fr auto",
    gap:"10px",
    alignItems:"center",
    padding:"14px",
    background:"rgba(255,250,244,0.8)",
    border:"1px solid "+UI.lineSoft,
    borderRadius:"22px",
    boxShadow:UI.shadowSoft,
  },
  dateBtn: {
    padding:"9px 12px",
    background:"rgba(255,251,246,0.92)",
    border:"1px solid "+UI.lineSoft,
    borderRadius:"14px",
    color:UI.inkSoft,
    fontSize:"12px",
    cursor:"pointer",
  },
  dateBtnDisabled: { opacity:0.45, cursor:"not-allowed" },
  dateCenter: { display:"flex",flexDirection:"column",alignItems:"center",gap:"3px",textAlign:"center" },
  dateMain: { fontSize:"17px",fontWeight:700,color:UI.ink },
  dateSub: { fontSize:"11px",color:UI.inkMute,fontFamily:mono,lineHeight:1.5 },
  dateMeta: { display:"flex",alignItems:"center",gap:"10px",marginTop:"10px",flexWrap:"wrap" },
  dateInput: {
    padding:"9px 12px",
    background:"rgba(255,251,246,0.92)",
    border:"1px solid "+UI.line,
    borderRadius:"14px",
    color:UI.ink,
    fontSize:"13px",
    fontFamily:mono,
    outline:"none",
    boxShadow:UI.shadowSoft,
  },
  todayBtn: {
    padding:"9px 13px",
    background:"linear-gradient(180deg, rgba(240,219,197,0.92) 0%, rgba(232,197,168,0.96) 100%)",
    border:"1px solid rgba(201,134,99,0.22)",
    borderRadius:"14px",
    color:UI.accentStrong,
    fontSize:"12px",
    cursor:"pointer",
    boxShadow:UI.shadowSoft,
  },
  tHead: { display:"flex",alignItems:"center",marginBottom:"18px",gap:"16px" },
  tTitle: { fontSize:"21px",fontWeight:700,margin:0,color:UI.ink },
  sec: {
    marginBottom:"22px",
    padding:"20px",
    background:"linear-gradient(180deg, rgba(255,251,246,0.97) 0%, rgba(247,236,223,0.93) 100%)",
    border:"1px solid "+UI.lineSoft,
    borderRadius:"20px",
    boxShadow:"0 8px 24px rgba(165, 128, 95, 0.08), 0 1px 3px rgba(165, 128, 95, 0.06)",
  },
  secT: { fontSize:"13px",color:UI.inkMute,fontWeight:700,margin:"0 0 14px",letterSpacing:"0.4px" },
  actionRow: { display:"flex",gap:"10px",flexWrap:"wrap",marginBottom:"8px" },
  actionBtn: {
    padding:"10px 15px",
    background:"rgba(255,250,244,0.88)",
    border:"1px solid "+UI.line,
    borderRadius:"14px",
    color:UI.ink,
    fontSize:"13px",
    cursor:"pointer",
    boxShadow:UI.shadowSoft,
  },
  actionBtnStrong: {
    padding:"10px 15px",
    background:"linear-gradient(180deg, rgba(240,219,197,0.92) 0%, rgba(232,197,168,0.96) 100%)",
    border:"1px solid rgba(201,134,99,0.26)",
    borderRadius:"14px",
    color:UI.accentStrong,
    fontSize:"13px",
    cursor:"pointer",
    boxShadow:"0 12px 24px rgba(201,134,99,0.16)",
  },
  todayLayout: {
    display:"grid",
    gridTemplateColumns:"minmax(0, 1.08fr) minmax(320px, 0.92fr)",
    gap:"20px",
    alignItems:"start",
  },
  todayMain: { minWidth:0, display:"flex", flexDirection:"column", gap:"0px" },
  todaySide: { minWidth:0, display:"flex", flexDirection:"column", gap:"18px", position:"sticky", top:"82px", alignSelf:"start" },
  sideCard: {
    padding:"20px",
    background:"linear-gradient(180deg, rgba(255,251,246,0.97) 0%, rgba(247,236,223,0.93) 100%)",
    border:"1px solid "+UI.lineSoft,
    borderRadius:"20px",
    boxShadow:"0 8px 24px rgba(165, 128, 95, 0.08), 0 1px 3px rgba(165, 128, 95, 0.06)",
  },
  timelineCard: {
    padding:"20px",
    background:"linear-gradient(180deg, rgba(255,251,246,0.97) 0%, rgba(247,236,223,0.93) 100%)",
    border:"1px solid "+UI.lineSoft,
    borderRadius:"20px",
    boxShadow:"0 8px 24px rgba(165, 128, 95, 0.08), 0 1px 3px rgba(165, 128, 95, 0.06)",
  },
  timelineHead: { display:"flex", justifyContent:"space-between", alignItems:"flex-start", gap:"12px", marginBottom:"12px" },
  timelineSub: { margin:"4px 0 0", fontSize:"12px", color:UI.inkMute, lineHeight:1.7 },
  timelineComposer: { display:"flex", gap:"6px", marginBottom:"14px" },
  timelineList: { display:"flex", flexDirection:"column", gap:"12px" },
  timelineScroll: { maxHeight:"560px", overflowY:"auto", paddingRight:"4px" },
  timelineGroup: { display:"flex", flexDirection:"column", gap:"8px" },
  timelineGroupHead: { display:"flex", alignItems:"center", gap:"8px", width:"100%", padding:"8px 0 4px" },
  timelineGroupLabel: { fontSize:"12px", fontWeight:700, color:UI.inkSoft, letterSpacing:"0.3px" },
  timelineItem: {
    display:"grid", gridTemplateColumns:"30px minmax(0, 1fr)", gap:"12px", alignItems:"start",
    width:"100%", background:"none", border:"none", textAlign:"left",
    paddingBottom:"12px", borderBottom:"1px solid "+UI.lineSoft, cursor:"default",
  },
  timelineItemInteractive: { cursor:"pointer" },
  timelineDot: { width:"30px", height:"30px", borderRadius:"999px", display:"flex", alignItems:"center", justifyContent:"center", color:"#fffaf2", fontSize:"14px", boxShadow:UI.shadowSoft },
  timelineBody: { minWidth:0 },
  timelineMeta: { display:"flex", alignItems:"flex-start", justifyContent:"space-between", gap:"10px", marginBottom:"4px" },
  timelineMetaMain: { flex:"1 1 auto", minWidth:0, display:"flex", alignItems:"center", gap:"8px", flexWrap:"wrap" },
  timelineTitle: { fontSize:"12px", fontWeight:700, minWidth:0, overflowWrap:"anywhere" },
  timelineTag: { flexShrink:0, fontSize:"10px", color:UI.inkMute, border:"1px solid "+UI.lineSoft, borderRadius:"999px", padding:"2px 7px", background:"rgba(255,250,244,0.84)" },
  timelineTime: { flexShrink:0, fontSize:"10px", color:UI.inkMute, fontFamily:mono },
  timelineText: { margin:0, fontSize:"13px", color:UI.inkSoft, lineHeight:1.75, whiteSpace:"pre-wrap" },
  timelineTextCompact: { margin:0, fontSize:"12px", color:UI.inkSoft, lineHeight:1.7, display:"-webkit-box", WebkitLineClamp:2, WebkitBoxOrient:"vertical", overflow:"hidden" },
  routineHead: { display:"flex", justifyContent:"space-between", alignItems:"flex-start", gap:"14px", marginBottom:"12px", flexWrap:"wrap" },
  routineSummary: { margin:"2px 0 0", fontSize:"12px", color:UI.inkMute, lineHeight:1.7 },
  routineStateBtn: { marginLeft:"auto", padding:"6px 10px", background:"rgba(255,250,244,0.88)", border:"1px solid", borderRadius:"999px", fontSize:"11px", cursor:"pointer" },
  routineStateBtnDone: { background:"rgba(245,250,240,0.92)" },
  routineToggleBtn: { padding:"6px 10px", background:"rgba(255,250,244,0.88)", border:"1px solid "+UI.lineSoft, borderRadius:"999px", fontSize:"11px", cursor:"pointer", color:UI.inkMute },
  routinePreview: { display:"flex", alignItems:"center", gap:"12px", padding:"12px 14px", border:"1px solid "+UI.lineSoft, borderRadius:"18px", background:"rgba(255,250,244,0.78)" },
  routinePreviewName: { margin:"0 0 3px", fontSize:"15px", fontWeight:700, color:UI.ink },
  routinePreviewPrompt: { margin:0, fontSize:"13px", color:UI.inkMute, lineHeight:1.7 },
  routineItemPreview: { margin:0, flex:1, fontSize:"13px", color:UI.inkSoft, lineHeight:1.65, display:"-webkit-box", WebkitLineClamp:2, WebkitBoxOrient:"vertical", overflow:"hidden" },
  routineItemFull: { margin:0, flex:1, fontSize:"13px", color:UI.inkSoft, lineHeight:1.7, whiteSpace:"pre-wrap" },
  routineItemActions: { display:"flex", alignItems:"center", gap:"4px" },
  routineEditWrap: { flex:1, display:"flex", flexDirection:"column", gap:"8px" },
  routineEditBox: { width:"100%", minHeight:"92px", boxSizing:"border-box", padding:"10px 12px", background:"rgba(255,251,246,0.92)", border:"1px solid "+UI.line, borderRadius:"12px", color:UI.ink, fontSize:"13px", lineHeight:1.7, resize:"vertical", outline:"none" },
  routineEditActions: { display:"flex", gap:"8px", justifyContent:"flex-end" },
  routineMoreHint: { margin:"2px 0 0", fontSize:"11px", color:UI.inkMute },
  routineComposer: { padding:"14px", marginBottom:"14px", background:"rgba(255,251,246,0.86)", border:"1px solid "+UI.lineSoft, borderRadius:"18px", boxShadow:"inset 0 1px 3px rgba(165,128,95,0.06)", display:"flex", flexDirection:"column", gap:"10px" },
  routineHint: { margin:0, fontSize:"12px", color:UI.inkMute, lineHeight:1.7 },
  routineList: { display:"flex", flexDirection:"column", gap:"10px" },
  routineRow: { display:"flex", justifyContent:"space-between", alignItems:"center", gap:"12px", padding:"12px 14px", border:"1px solid "+UI.lineSoft, borderRadius:"18px", background:"rgba(255,251,246,0.82)", boxShadow:UI.shadowSoft, flexWrap:"wrap" },
  routineRowDone: { background:"linear-gradient(180deg, rgba(248,252,244,0.95) 0%, rgba(240,246,234,0.92) 100%)", borderColor:"rgba(147,167,131,0.24)" },
  routineToggle: { flex:"1 1 220px", minWidth:0, display:"flex", alignItems:"center", gap:"12px", background:"none", border:"none", padding:0, cursor:"pointer", textAlign:"left" },
  routineCheck: { width:"22px", height:"22px", borderRadius:"999px", border:"1px solid "+UI.line, background:"rgba(255,250,244,0.9)", color:"transparent", display:"flex", alignItems:"center", justifyContent:"center", fontSize:"13px", flexShrink:0, boxShadow:"inset 0 1px 2px rgba(165,128,95,0.08)" },
  routineCheckDone: { background:"linear-gradient(180deg, rgba(166,186,145,0.98) 0%, rgba(144,168,123,0.94) 100%)", borderColor:"rgba(126,149,107,0.5)", color:"#fffaf2", boxShadow:"0 8px 18px rgba(144,168,123,0.18)" },
  routineName: { fontSize:"14px", color:UI.inkSoft, lineHeight:1.7 },
  routineNameDone: { color:UI.inkMute, textDecoration:"line-through" },
  routineRowActions: { display:"flex", alignItems:"center", gap:"8px", flexWrap:"wrap" },
  routineEmpty: { padding:"18px", border:"1px dashed "+UI.line, borderRadius:"18px", background:"rgba(255,251,246,0.7)" },
  routineInactiveBox: { marginTop:"14px", paddingTop:"14px", borderTop:"1px solid "+UI.lineSoft },
  routineInactiveHead: { display:"flex", alignItems:"center", gap:"8px", marginBottom:"10px" },
  routineInactiveList: { display:"flex", flexDirection:"column", gap:"8px" },
  routineInactiveRow: { display:"flex", justifyContent:"space-between", alignItems:"center", gap:"10px", padding:"10px 12px", background:"rgba(255,250,244,0.76)", border:"1px solid "+UI.lineSoft, borderRadius:"16px", flexWrap:"wrap" },
  routineInactiveMeta: { display:"flex", alignItems:"center", gap:"8px", flexWrap:"wrap" },
  routineInactiveName: { fontSize:"13px", color:UI.inkMute, lineHeight:1.6 },
  tEntry: { borderLeft:"3px solid",paddingLeft:"12px",marginBottom:"12px" },
  tEntryHead: { display:"flex",alignItems:"center",gap:"6px",marginBottom:"5px",flexWrap:"wrap" },
  tStage: { fontSize:"10px",color:UI.inkMute,background:"rgba(255,250,244,0.8)",border:"1px solid "+UI.lineSoft,padding:"2px 7px",borderRadius:"999px" },
  qGrid: { display:"grid",gridTemplateColumns:"1fr 1fr",gap:"10px" },
  qBtn: { padding:"16px 14px", background:"linear-gradient(180deg, rgba(255,251,246,0.96) 0%, rgba(246,235,223,0.92) 100%)", border:"1px solid", borderRadius:"18px", cursor:"pointer", display:"flex", flexDirection:"column", alignItems:"center", gap:"6px", boxShadow:UI.shadowSoft },
  logW: { borderLeft:"4px solid", padding:"16px 16px 16px 18px", marginBottom:"14px", background:"rgba(255,251,246,0.82)", borderRadius:"16px", border:"1px solid "+UI.lineSoft, boxShadow:"0 4px 16px rgba(165, 128, 95, 0.06)" },
  logH: { display:"flex",alignItems:"center",gap:"8px",marginBottom:"8px" },
  logC: { fontSize:"11px",color:UI.inkMute,fontFamily:mono,marginLeft:"auto" },
  logE: { display:"flex",alignItems:"flex-start",gap:"8px",marginBottom:"6px" },
  refBox: { width:"100%", minHeight:"150px", background:"rgba(255,251,246,0.88)", border:"1px solid "+UI.line, borderRadius:"18px", color:UI.ink, fontSize:"14px", padding:"16px", resize:"vertical", outline:"none", lineHeight:1.85, boxSizing:"border-box", boxShadow:"inset 0 1px 3px rgba(165,128,95,0.06)" },
  fbBox: { padding:"20px", background:"linear-gradient(135deg, rgba(252,245,236,0.96) 0%, rgba(242,225,203,0.92) 100%)", border:"1px solid rgba(201,134,99,0.18)", borderRadius:"22px", marginBottom:"24px", boxShadow:UI.shadowSoft },
  fbNote: { fontSize:"13px",color:UI.inkSoft,margin:"0 0 7px",lineHeight:1.7 },
  projectsPageHead: { display:"flex", justifyContent:"space-between", alignItems:"flex-start", gap:"14px", marginBottom:"16px", flexWrap:"wrap" },
  projectsToolbar: { marginBottom:"16px" },
  typePageHead: { display:"flex", justifyContent:"space-between", alignItems:"flex-start", gap:"14px", marginBottom:"18px", flexWrap:"wrap" },
  typePageTitle: { fontSize:"22px", fontWeight:700, margin:"0 0 6px", color:UI.ink },
  typePageSub: { margin:0, fontSize:"13px", color:UI.inkMute, lineHeight:1.8, maxWidth:"460px" },
  typeNotice: { padding:"12px 14px", marginBottom:"16px", background:"rgba(255,250,244,0.9)", border:"1px solid "+UI.line, borderRadius:"16px", color:UI.accentStrong, fontSize:"13px", lineHeight:1.7, boxShadow:UI.shadowSoft },
  typeCardList: { display:"flex", flexDirection:"column", gap:"16px" },
  typeCard: { padding:"20px", background:"linear-gradient(180deg, rgba(255,251,246,0.97) 0%, rgba(247,236,223,0.93) 100%)", border:"1px solid "+UI.lineSoft, borderRadius:"20px", boxShadow:"0 8px 24px rgba(165, 128, 95, 0.08), 0 1px 3px rgba(165, 128, 95, 0.06)" },
  typeCardHead: { display:"flex", justifyContent:"space-between", alignItems:"flex-start", gap:"14px", marginBottom:"12px", flexWrap:"wrap" },
  typeIcon: { width:"46px", height:"46px", borderRadius:"14px", border:"1px solid", display:"flex", alignItems:"center", justifyContent:"center", background:"rgba(255,250,244,0.9)", fontSize:"20px", boxShadow:"0 4px 12px rgba(165, 128, 95, 0.08)" },
  typeNameRow: { display:"flex", alignItems:"center", gap:"8px", flexWrap:"wrap" },
  typeName: { fontSize:"17px", fontWeight:700, margin:0, color:UI.ink },
  typeInactive: { fontSize:"10px", color:UI.inkMute, border:"1px solid "+UI.lineSoft, borderRadius:"999px", padding:"3px 8px", background:"rgba(255,250,244,0.78)" },
  typeMeta: { margin:"4px 0 0", fontSize:"12px", color:UI.inkMute, fontFamily:mono },
  typeHeadActions: { display:"flex", gap:"8px", flexWrap:"wrap" },
  typeStageStrip: { display:"flex", gap:"8px", flexWrap:"wrap" },
  typeStagePill: { padding:"6px 13px", border:"1px solid", borderRadius:"999px", fontSize:"12px", background:"rgba(255,250,244,0.9)", fontWeight:500 },
  typeEditor: { marginTop:"14px", padding:"16px", background:"rgba(255,251,246,0.84)", border:"1px solid "+UI.lineSoft, borderRadius:"18px", boxShadow:"inset 0 1px 3px rgba(165,128,95,0.06)", display:"flex", flexDirection:"column", gap:"14px" },
  typeEditorGrid: { display:"grid", gridTemplateColumns:"repeat(auto-fit, minmax(160px, 1fr))", gap:"12px" },
  fieldLabel: { display:"flex", flexDirection:"column", gap:"7px", fontSize:"12px", color:UI.inkMute },
  selectInput: { padding:"11px 14px", background:"rgba(255,251,246,0.92)", border:"1px solid "+UI.line, borderRadius:"14px", color:UI.ink, fontSize:"14px", outline:"none" },
  colorRow: { display:"flex", alignItems:"center", gap:"10px" },
  colorInput: { width:"46px", height:"42px", padding:"4px", border:"1px solid "+UI.line, borderRadius:"12px", background:"rgba(255,251,246,0.92)", cursor:"pointer" },
  typeSectionHead: { display:"flex", justifyContent:"space-between", alignItems:"center", gap:"12px", marginBottom:"8px", flexWrap:"wrap" },
  fieldSectionTitle: { fontSize:"12px", color:UI.inkMute, fontWeight:700, letterSpacing:"0.3px" },
  stageEditorRow: { display:"grid", gridTemplateColumns:"1fr auto", gap:"8px", alignItems:"center", marginBottom:"8px" },
  stageEditorActions: { display:"flex", gap:"6px" },
  typeEditorActions: { display:"flex", gap:"10px", flexWrap:"wrap" },
  miniBtn: { padding:"8px 14px", background:"rgba(255,250,244,0.92)", border:"1px solid "+UI.lineSoft, borderRadius:"10px", color:UI.inkSoft, fontSize:"12px", cursor:"pointer" },
  miniBtnDisabled: { padding:"8px 14px", background:"rgba(255,250,244,0.7)", border:"1px solid "+UI.lineSoft, borderRadius:"10px", color:UI.inkFaint, fontSize:"12px", cursor:"not-allowed", opacity:0.5 },
  projectGroupList: { display:"flex", flexDirection:"column", gap:"16px" },
  projectGroupCard: { padding:"18px", background:"linear-gradient(180deg, rgba(255,250,244,0.95) 0%, rgba(247,236,223,0.92) 100%)", border:"1px solid "+UI.lineSoft, borderRadius:"22px", boxShadow:UI.shadowSoft },
  projectGroupHead: { display:"flex", justifyContent:"space-between", alignItems:"flex-start", gap:"14px", marginBottom:"14px", flexWrap:"wrap" },
  projectList: { display:"flex", flexDirection:"column", gap:"10px" },
  projectRowCard: { display:"flex", justifyContent:"space-between", alignItems:"center", gap:"12px", padding:"14px", border:"1px solid "+UI.lineSoft, borderRadius:"18px", background:"rgba(255,251,246,0.88)", boxShadow:UI.shadowSoft, flexWrap:"wrap" },
  projectRowMain: { flex:"1 1 260px", minWidth:0 },
  projectRowTitle: { display:"flex", alignItems:"center", gap:"8px", flexWrap:"wrap", marginBottom:"6px" },
  projectRowName: { fontSize:"15px", fontWeight:700, color:UI.ink },
  projectRowMeta: { margin:0, fontSize:"12px", color:UI.inkMute, lineHeight:1.7, fontFamily:mono },
  projectRowActions: { display:"flex", gap:"8px", flexWrap:"wrap" },
  projectEmptyText: { margin:"0", fontSize:"13px", color:UI.inkMute, lineHeight:1.8, fontStyle:"italic" },
  pipelineDate: { margin:0, fontSize:"12px", color:UI.inkMute, lineHeight:1.5 },
  addPBtn: { padding:"9px 16px", background:"rgba(255,250,244,0.84)", border:"1px solid", borderRadius:"999px", fontSize:"13px", cursor:"pointer", boxShadow:UI.shadowSoft },
  addForm: { padding:"20px", background:"linear-gradient(180deg, rgba(255,251,246,0.97) 0%, rgba(247,236,223,0.93) 100%)", border:"1px solid "+UI.lineSoft, borderRadius:"20px", marginBottom:"20px", display:"flex", flexDirection:"column", gap:"12px", boxShadow:"0 8px 24px rgba(165, 128, 95, 0.08), 0 1px 3px rgba(165, 128, 95, 0.06)" },
  addInp: { padding:"11px 14px", background:"rgba(255,251,246,0.92)", border:"1px solid "+UI.line, borderRadius:"14px", color:UI.ink, fontSize:"14px", outline:"none" },
  pill: { padding:"6px 14px", background:"rgba(255,250,244,0.8)", border:"1px solid "+UI.lineSoft, borderRadius:"999px", color:UI.inkMute, fontSize:"12px", cursor:"pointer", transition:"all 0.15s" },
  pillSm: { padding:"4px 10px", background:"rgba(255,250,244,0.8)", border:"1px solid "+UI.lineSoft, borderRadius:"999px", color:UI.inkMute, fontSize:"11px", cursor:"pointer" },
  cfmBtn: { padding:"9px 20px",border:"1px solid",borderRadius:"14px",fontSize:"13px",cursor:"pointer" },
  canBtn: { padding:"9px 20px", background:"rgba(255,250,244,0.84)", border:"1px solid "+UI.lineSoft, borderRadius:"14px", color:UI.inkSoft, fontSize:"13px", cursor:"pointer" },
  cnt: { fontSize:"11px",color:UI.inkMute,background:"rgba(255,250,244,0.84)",border:"1px solid "+UI.lineSoft,padding:"2px 8px",borderRadius:"999px",fontFamily:mono },
  emptyState: { padding:"24px 18px", border:"1px solid", borderRadius:"22px", marginBottom:"20px", boxShadow:UI.shadowSoft, textAlign:"center" },
  emptyTitle: { fontSize:"17px", fontWeight:700, margin:"8px 0 8px" },
  emptyText: { fontSize:"13px", color:UI.inkSoft, margin:"0 auto 14px", lineHeight:1.8, maxWidth:"420px" },
  emptyCta: { padding:"9px 16px", background:"rgba(255,250,244,0.92)", border:"1px solid", borderRadius:"999px", fontSize:"13px", cursor:"pointer", boxShadow:UI.shadowSoft },
  tBadge: { fontSize:"10px",color:UI.sage,background:"rgba(147,167,131,0.12)",padding:"2px 8px",borderRadius:"999px" },
  dLabel: { fontSize:"11px",color:UI.inkMute,display:"block",marginBottom:"4px" },
  eRow: { display:"flex",alignItems:"flex-start",gap:"6px",marginBottom:"5px",paddingLeft:"4px" },
  projectEntryBlock: { marginBottom:"7px" },
  projectNoteList: { marginLeft:"18px", paddingLeft:"10px", borderLeft:"1px dashed "+UI.lineSoft },
  projectNoteRow: { display:"flex", alignItems:"flex-start", gap:"6px", marginBottom:"5px" },
  projectNoteDot: { fontSize:"11px", color:UI.inkFaint, lineHeight:1.7, flexShrink:0 },
  projectNoteText: { flex:1, fontSize:"12px", color:UI.inkSoft, lineHeight:1.7 },
  renameBlock: { marginBottom:"12px", padding:"12px 14px", background:"rgba(255,251,246,0.86)", border:"1px solid "+UI.lineSoft, borderRadius:"16px", boxShadow:"inset 0 1px 3px rgba(165,128,95,0.06)" },
  renameLabel: { display:"block", marginBottom:"8px", fontSize:"11px", color:UI.inkMute },
  renameRow: { display:"flex", gap:"8px", alignItems:"center", flexWrap:"wrap" },
  renameInp: { flex:"1 1 220px", minWidth:0, padding:"10px 12px", background:"rgba(255,251,246,0.96)", border:"1px solid "+UI.line, borderRadius:"12px", color:UI.ink, fontSize:"13px", outline:"none" },
  archivedRenameWrap: { flex:1, minWidth:0, display:"flex", alignItems:"center", gap:"8px", flexWrap:"wrap" },
  archivedRenameInp: { flex:"1 1 200px", minWidth:0, padding:"8px 10px", background:"rgba(255,251,246,0.96)", border:"1px solid "+UI.line, borderRadius:"12px", color:UI.ink, fontSize:"12px", outline:"none" },
  multiInputRow: { display:"flex", gap:"6px", marginTop:"6px", alignItems:"flex-end" },
  multiInp: { flex:1, minHeight:"56px", maxHeight:"320px", padding:"12px 14px", background:"rgba(255,251,246,0.92)", border:"1px solid "+UI.line, borderRadius:"16px", color:UI.ink, fontSize:"13px", lineHeight:1.8, outline:"none", resize:"none", overflow:"hidden", boxSizing:"border-box", boxShadow:"inset 0 1px 3px rgba(165,128,95,0.06)" },
  inp: { flex:1, padding:"9px 12px", background:"rgba(255,251,246,0.92)", border:"1px solid "+UI.line, borderRadius:"12px", color:UI.ink, fontSize:"13px", outline:"none" },
  addB: { width:"36px", background:"linear-gradient(180deg, rgba(240,219,197,0.92) 0%, rgba(232,197,168,0.96) 100%)", border:"1px solid rgba(201,134,99,0.22)", borderRadius:"12px", color:UI.accentStrong, fontSize:"16px", cursor:"pointer", boxShadow:UI.shadowSoft },
  xBtn: { background:"none",border:"none",color:UI.inkFaint,fontSize:"14px",cursor:"pointer",padding:"0 4px",lineHeight:1 },
  aBtn: { background:"none",border:"none",color:UI.inkMute,fontSize:"12px",cursor:"pointer",padding:"4px 8px" },
};
